name: Run build_runner on main
on:
  push:
    paths:
      - 'lib/api/definition/batt-kit.json'
jobs:
  build_runner:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes to the repository
      pull-requests: write  # Required to create PRs
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to fetch all history for merging

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Set your Flutter version here

      - name: Get dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build --delete-conflicting-outputs  

      - name: Commit and push changes (if any)
        id: commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-generated code from build_runner"
            git push origin ${{ github.ref_name }}
          fi

      - name: Create PR on merge conflict
        if: steps.commit.outcome == 'failure'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Auto-generated code from build_runner"
          title: "Merge build_runner generated changes"
          body: "This PR contains auto-generated code from build_runner."
          branch: "build_runner-updates"
          base: main