name: Run build_runner on main

on:
  push:
    branches: [ main ]

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run build_runner
        run: dart run build_runner build