name: Run build_runner on main

on:
  push:
    branches: [ main ]

jobs:
  build_runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'  # Set your Flutter version here
  
      - name: Check dart formatting (run dart format)
        run: dart format --output none --set-exit-if-changed .
  
      - name: Get dependencies
        run: flutter pub get

      - name: Run build_runner
        run: dart run build_runner build